# Generated by Django 4.0.6 on 2022-08-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
            ],
            options={
                'verbose_name': 'Control Panel',
                'verbose_name_plural': 'Control Panel',
            },
        ),
    ]
