# Generated by Django 4.0.6 on 2022-08-05 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobberCalendar', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ControlPanel',
        ),
    ]
